// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simulador.App.Data;

#nullable disable

namespace Simulador.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310215636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simulador.App.Modules.Catalog.Entities.PriceAverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("CompanyBilling")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyBilling", "Sku")
                        .IsUnique();

                    b.ToTable("PriceAverages");
                });

            modelBuilder.Entity("Simulador.App.Modules.Catalog.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PackagingType")
                        .HasColumnType("text");

                    b.Property<int>("PalletUnitsDefault")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Simulador.App.Modules.Catalog.Entities.SkuRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValidForSale")
                        .HasColumnType("boolean");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("SkuRules");
                });

            modelBuilder.Entity("Simulador.App.Modules.Config.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultLossPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FreightAcceptablePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FreightIdealPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MissingPricePolicy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("Simulador.App.Modules.Customers.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Simulador.App.Modules.Customers.Entities.CustomerAllowedVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "VehicleName");

                    b.ToTable("CustomerAllowedVehicles");
                });

            modelBuilder.Entity("Simulador.App.Modules.Customers.Entities.CustomerRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsBulk")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsMix")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsPalletized")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BulkPerM3Fee")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BulkPerTonFee")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxKgPerPallet")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NoShowFee")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PalletFee")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PalletMaxHeight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PalletRedoFee")
                        .HasColumnType("numeric");

                    b.Property<string>("PalletType")
                        .HasColumnType("text");

                    b.Property<decimal?>("SchedulingFee")
                        .HasColumnType("numeric");

                    b.Property<string>("SkuPerPalletPolicy")
                        .HasColumnType("text");

                    b.Property<decimal?>("StretchFee")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerRules");
                });

            modelBuilder.Entity("Simulador.App.Modules.Simulations.Entities.SimulationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("PalletUnitsOverride")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPriceInput")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.ToTable("SimulationItems");
                });

            modelBuilder.Entity("Simulador.App.Modules.Simulations.Entities.SimulationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyBilling")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FreightAcceptablePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FreightIdealPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPalletized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LossPercentApplied")
                        .HasColumnType("numeric");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SimulationRuns");
                });

            modelBuilder.Entity("Simulador.App.Modules.Vehicles.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPallets")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxVolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Simulador.App.Modules.Customers.Entities.CustomerAllowedVehicle", b =>
                {
                    b.HasOne("Simulador.App.Modules.Customers.Entities.Customer", null)
                        .WithMany("AllowedVehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Simulador.App.Modules.Customers.Entities.CustomerRules", b =>
                {
                    b.HasOne("Simulador.App.Modules.Customers.Entities.Customer", "Customer")
                        .WithOne("Rules")
                        .HasForeignKey("Simulador.App.Modules.Customers.Entities.CustomerRules", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Simulador.App.Modules.Simulations.Entities.SimulationItem", b =>
                {
                    b.HasOne("Simulador.App.Modules.Simulations.Entities.SimulationRun", "SimulationRun")
                        .WithMany("Items")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Simulador.App.Modules.Customers.Entities.Customer", b =>
                {
                    b.Navigation("AllowedVehicles");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Simulador.App.Modules.Simulations.Entities.SimulationRun", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
